/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiClient;
import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.ApiResponse;
import com.templatefox.sdk.Configuration;
import com.templatefox.sdk.Pair;

import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.S3ConfigRequest;
import com.templatefox.sdk.model.S3ConfigResponse;
import com.templatefox.sdk.model.S3SuccessResponse;
import com.templatefox.sdk.model.S3TestResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class IntegrationsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public IntegrationsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public IntegrationsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Delete S3 configuration
   * Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return S3SuccessResponse
   * @throws ApiException if fails to make API call
   */
  public S3SuccessResponse deleteS3Config() throws ApiException {
    return deleteS3Config(null);
  }

  /**
   * Delete S3 configuration
   * Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return S3SuccessResponse
   * @throws ApiException if fails to make API call
   */
  public S3SuccessResponse deleteS3Config(Map<String, String> headers) throws ApiException {
    ApiResponse<S3SuccessResponse> localVarResponse = deleteS3ConfigWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Delete S3 configuration
   * Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return ApiResponse&lt;S3SuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3SuccessResponse> deleteS3ConfigWithHttpInfo() throws ApiException {
    return deleteS3ConfigWithHttpInfo(null);
  }

  /**
   * Delete S3 configuration
   * Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;S3SuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3SuccessResponse> deleteS3ConfigWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteS3ConfigRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteS3Config", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<S3SuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        S3SuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<S3SuccessResponse>() {});
        

        return new ApiResponse<S3SuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteS3ConfigRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/integrations/s3";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get S3 configuration
   * Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return S3ConfigResponse
   * @throws ApiException if fails to make API call
   */
  public S3ConfigResponse getS3Config() throws ApiException {
    return getS3Config(null);
  }

  /**
   * Get S3 configuration
   * Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return S3ConfigResponse
   * @throws ApiException if fails to make API call
   */
  public S3ConfigResponse getS3Config(Map<String, String> headers) throws ApiException {
    ApiResponse<S3ConfigResponse> localVarResponse = getS3ConfigWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get S3 configuration
   * Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return ApiResponse&lt;S3ConfigResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3ConfigResponse> getS3ConfigWithHttpInfo() throws ApiException {
    return getS3ConfigWithHttpInfo(null);
  }

  /**
   * Get S3 configuration
   * Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;S3ConfigResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3ConfigResponse> getS3ConfigWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getS3ConfigRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getS3Config", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<S3ConfigResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        S3ConfigResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<S3ConfigResponse>() {});
        

        return new ApiResponse<S3ConfigResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getS3ConfigRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/integrations/s3";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Save S3 configuration
   * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param s3ConfigRequest  (required)
   * @return S3SuccessResponse
   * @throws ApiException if fails to make API call
   */
  public S3SuccessResponse saveS3Config(@jakarta.annotation.Nonnull S3ConfigRequest s3ConfigRequest) throws ApiException {
    return saveS3Config(s3ConfigRequest, null);
  }

  /**
   * Save S3 configuration
   * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param s3ConfigRequest  (required)
   * @param headers Optional headers to include in the request
   * @return S3SuccessResponse
   * @throws ApiException if fails to make API call
   */
  public S3SuccessResponse saveS3Config(@jakarta.annotation.Nonnull S3ConfigRequest s3ConfigRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<S3SuccessResponse> localVarResponse = saveS3ConfigWithHttpInfo(s3ConfigRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Save S3 configuration
   * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param s3ConfigRequest  (required)
   * @return ApiResponse&lt;S3SuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3SuccessResponse> saveS3ConfigWithHttpInfo(@jakarta.annotation.Nonnull S3ConfigRequest s3ConfigRequest) throws ApiException {
    return saveS3ConfigWithHttpInfo(s3ConfigRequest, null);
  }

  /**
   * Save S3 configuration
   * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param s3ConfigRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;S3SuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3SuccessResponse> saveS3ConfigWithHttpInfo(@jakarta.annotation.Nonnull S3ConfigRequest s3ConfigRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = saveS3ConfigRequestBuilder(s3ConfigRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("saveS3Config", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<S3SuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        S3SuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<S3SuccessResponse>() {});
        

        return new ApiResponse<S3SuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder saveS3ConfigRequestBuilder(@jakarta.annotation.Nonnull S3ConfigRequest s3ConfigRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 's3ConfigRequest' is set
    if (s3ConfigRequest == null) {
      throw new ApiException(400, "Missing the required parameter 's3ConfigRequest' when calling saveS3Config");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/integrations/s3";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(s3ConfigRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Test S3 connection
   * Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return S3TestResponse
   * @throws ApiException if fails to make API call
   */
  public S3TestResponse testS3Connection() throws ApiException {
    return testS3Connection(null);
  }

  /**
   * Test S3 connection
   * Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return S3TestResponse
   * @throws ApiException if fails to make API call
   */
  public S3TestResponse testS3Connection(Map<String, String> headers) throws ApiException {
    ApiResponse<S3TestResponse> localVarResponse = testS3ConnectionWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Test S3 connection
   * Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @return ApiResponse&lt;S3TestResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3TestResponse> testS3ConnectionWithHttpInfo() throws ApiException {
    return testS3ConnectionWithHttpInfo(null);
  }

  /**
   * Test S3 connection
   * Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;S3TestResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<S3TestResponse> testS3ConnectionWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = testS3ConnectionRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("testS3Connection", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<S3TestResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        S3TestResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<S3TestResponse>() {});
        

        return new ApiResponse<S3TestResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder testS3ConnectionRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/integrations/s3/test";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
