/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiClient;
import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.ApiResponse;
import com.templatefox.sdk.Configuration;
import com.templatefox.sdk.Pair;

import com.templatefox.sdk.model.CreateAsyncPdfRequest;
import com.templatefox.sdk.model.CreateAsyncPdfResponse;
import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.JobListResponse;
import com.templatefox.sdk.model.JobStatus;
import com.templatefox.sdk.model.JobStatusResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class PdfAsyncApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PdfAsyncApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PdfAsyncApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Generate PDF asynchronously
   * Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
   * @param createAsyncPdfRequest  (required)
   * @return CreateAsyncPdfResponse
   * @throws ApiException if fails to make API call
   */
  public CreateAsyncPdfResponse createPdfAsync(@jakarta.annotation.Nonnull CreateAsyncPdfRequest createAsyncPdfRequest) throws ApiException {
    return createPdfAsync(createAsyncPdfRequest, null);
  }

  /**
   * Generate PDF asynchronously
   * Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
   * @param createAsyncPdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateAsyncPdfResponse
   * @throws ApiException if fails to make API call
   */
  public CreateAsyncPdfResponse createPdfAsync(@jakarta.annotation.Nonnull CreateAsyncPdfRequest createAsyncPdfRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateAsyncPdfResponse> localVarResponse = createPdfAsyncWithHttpInfo(createAsyncPdfRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Generate PDF asynchronously
   * Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
   * @param createAsyncPdfRequest  (required)
   * @return ApiResponse&lt;CreateAsyncPdfResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateAsyncPdfResponse> createPdfAsyncWithHttpInfo(@jakarta.annotation.Nonnull CreateAsyncPdfRequest createAsyncPdfRequest) throws ApiException {
    return createPdfAsyncWithHttpInfo(createAsyncPdfRequest, null);
  }

  /**
   * Generate PDF asynchronously
   * Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
   * @param createAsyncPdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateAsyncPdfResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateAsyncPdfResponse> createPdfAsyncWithHttpInfo(@jakarta.annotation.Nonnull CreateAsyncPdfRequest createAsyncPdfRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createPdfAsyncRequestBuilder(createAsyncPdfRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createPdfAsync", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateAsyncPdfResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateAsyncPdfResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateAsyncPdfResponse>() {});
        

        return new ApiResponse<CreateAsyncPdfResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createPdfAsyncRequestBuilder(@jakarta.annotation.Nonnull CreateAsyncPdfRequest createAsyncPdfRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createAsyncPdfRequest' is set
    if (createAsyncPdfRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createAsyncPdfRequest' when calling createPdfAsync");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf/create-async";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createAsyncPdfRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get PDF job status
   * Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
   * @param jobId  (required)
   * @return JobStatusResponse
   * @throws ApiException if fails to make API call
   */
  public JobStatusResponse getPdfJob(@jakarta.annotation.Nonnull String jobId) throws ApiException {
    return getPdfJob(jobId, null);
  }

  /**
   * Get PDF job status
   * Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
   * @param jobId  (required)
   * @param headers Optional headers to include in the request
   * @return JobStatusResponse
   * @throws ApiException if fails to make API call
   */
  public JobStatusResponse getPdfJob(@jakarta.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    ApiResponse<JobStatusResponse> localVarResponse = getPdfJobWithHttpInfo(jobId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get PDF job status
   * Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
   * @param jobId  (required)
   * @return ApiResponse&lt;JobStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobStatusResponse> getPdfJobWithHttpInfo(@jakarta.annotation.Nonnull String jobId) throws ApiException {
    return getPdfJobWithHttpInfo(jobId, null);
  }

  /**
   * Get PDF job status
   * Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
   * @param jobId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;JobStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobStatusResponse> getPdfJobWithHttpInfo(@jakarta.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPdfJobRequestBuilder(jobId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPdfJob", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<JobStatusResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        JobStatusResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<JobStatusResponse>() {});
        

        return new ApiResponse<JobStatusResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPdfJobRequestBuilder(@jakarta.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getPdfJob");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf/jobs/{job_id}"
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List PDF jobs
   * List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
   * @param limit  (optional, default to 20)
   * @param offset  (optional, default to 0)
   * @param status  (optional)
   * @return JobListResponse
   * @throws ApiException if fails to make API call
   */
  public JobListResponse listPdfJobs(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable Integer offset, @jakarta.annotation.Nullable JobStatus status) throws ApiException {
    return listPdfJobs(limit, offset, status, null);
  }

  /**
   * List PDF jobs
   * List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
   * @param limit  (optional, default to 20)
   * @param offset  (optional, default to 0)
   * @param status  (optional)
   * @param headers Optional headers to include in the request
   * @return JobListResponse
   * @throws ApiException if fails to make API call
   */
  public JobListResponse listPdfJobs(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable Integer offset, @jakarta.annotation.Nullable JobStatus status, Map<String, String> headers) throws ApiException {
    ApiResponse<JobListResponse> localVarResponse = listPdfJobsWithHttpInfo(limit, offset, status, headers);
    return localVarResponse.getData();
  }

  /**
   * List PDF jobs
   * List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
   * @param limit  (optional, default to 20)
   * @param offset  (optional, default to 0)
   * @param status  (optional)
   * @return ApiResponse&lt;JobListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobListResponse> listPdfJobsWithHttpInfo(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable Integer offset, @jakarta.annotation.Nullable JobStatus status) throws ApiException {
    return listPdfJobsWithHttpInfo(limit, offset, status, null);
  }

  /**
   * List PDF jobs
   * List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
   * @param limit  (optional, default to 20)
   * @param offset  (optional, default to 0)
   * @param status  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;JobListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobListResponse> listPdfJobsWithHttpInfo(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable Integer offset, @jakarta.annotation.Nullable JobStatus status, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPdfJobsRequestBuilder(limit, offset, status, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listPdfJobs", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<JobListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        JobListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<JobListResponse>() {});
        

        return new ApiResponse<JobListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPdfJobsRequestBuilder(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable Integer offset, @jakarta.annotation.Nullable JobStatus status, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf/jobs";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
