/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiClient;
import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.ApiResponse;
import com.templatefox.sdk.Configuration;
import com.templatefox.sdk.Pair;

import com.templatefox.sdk.model.ExtractPdfPagesRequest;
import com.templatefox.sdk.model.MergePdfRequest;
import com.templatefox.sdk.model.PdfToolsResponse;
import com.templatefox.sdk.model.RotatePdfRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PdfToolsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PdfToolsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PdfToolsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Extract pages from a PDF
   * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
   * @param extractPdfPagesRequest  (required)
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse extractPdfPages(@jakarta.annotation.Nonnull ExtractPdfPagesRequest extractPdfPagesRequest) throws ApiException {
    return extractPdfPages(extractPdfPagesRequest, null);
  }

  /**
   * Extract pages from a PDF
   * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
   * @param extractPdfPagesRequest  (required)
   * @param headers Optional headers to include in the request
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse extractPdfPages(@jakarta.annotation.Nonnull ExtractPdfPagesRequest extractPdfPagesRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<PdfToolsResponse> localVarResponse = extractPdfPagesWithHttpInfo(extractPdfPagesRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Extract pages from a PDF
   * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
   * @param extractPdfPagesRequest  (required)
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> extractPdfPagesWithHttpInfo(@jakarta.annotation.Nonnull ExtractPdfPagesRequest extractPdfPagesRequest) throws ApiException {
    return extractPdfPagesWithHttpInfo(extractPdfPagesRequest, null);
  }

  /**
   * Extract pages from a PDF
   * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
   * @param extractPdfPagesRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> extractPdfPagesWithHttpInfo(@jakarta.annotation.Nonnull ExtractPdfPagesRequest extractPdfPagesRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = extractPdfPagesRequestBuilder(extractPdfPagesRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("extractPdfPages", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PdfToolsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PdfToolsResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PdfToolsResponse>() {});
        

        return new ApiResponse<PdfToolsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder extractPdfPagesRequestBuilder(@jakarta.annotation.Nonnull ExtractPdfPagesRequest extractPdfPagesRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'extractPdfPagesRequest' is set
    if (extractPdfPagesRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'extractPdfPagesRequest' when calling extractPdfPages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf-tools/extract-pages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(extractPdfPagesRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Merge PDFs
   * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
   * @param mergePdfRequest  (required)
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse mergePdf(@jakarta.annotation.Nonnull MergePdfRequest mergePdfRequest) throws ApiException {
    return mergePdf(mergePdfRequest, null);
  }

  /**
   * Merge PDFs
   * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
   * @param mergePdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse mergePdf(@jakarta.annotation.Nonnull MergePdfRequest mergePdfRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<PdfToolsResponse> localVarResponse = mergePdfWithHttpInfo(mergePdfRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Merge PDFs
   * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
   * @param mergePdfRequest  (required)
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> mergePdfWithHttpInfo(@jakarta.annotation.Nonnull MergePdfRequest mergePdfRequest) throws ApiException {
    return mergePdfWithHttpInfo(mergePdfRequest, null);
  }

  /**
   * Merge PDFs
   * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
   * @param mergePdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> mergePdfWithHttpInfo(@jakarta.annotation.Nonnull MergePdfRequest mergePdfRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = mergePdfRequestBuilder(mergePdfRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("mergePdf", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PdfToolsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PdfToolsResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PdfToolsResponse>() {});
        

        return new ApiResponse<PdfToolsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder mergePdfRequestBuilder(@jakarta.annotation.Nonnull MergePdfRequest mergePdfRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'mergePdfRequest' is set
    if (mergePdfRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'mergePdfRequest' when calling mergePdf");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf-tools/merge";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(mergePdfRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rotate pages of a PDF
   * Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
   * @param rotatePdfRequest  (required)
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse rotatePdf(@jakarta.annotation.Nonnull RotatePdfRequest rotatePdfRequest) throws ApiException {
    return rotatePdf(rotatePdfRequest, null);
  }

  /**
   * Rotate pages of a PDF
   * Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
   * @param rotatePdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return PdfToolsResponse
   * @throws ApiException if fails to make API call
   */
  public PdfToolsResponse rotatePdf(@jakarta.annotation.Nonnull RotatePdfRequest rotatePdfRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<PdfToolsResponse> localVarResponse = rotatePdfWithHttpInfo(rotatePdfRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Rotate pages of a PDF
   * Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
   * @param rotatePdfRequest  (required)
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> rotatePdfWithHttpInfo(@jakarta.annotation.Nonnull RotatePdfRequest rotatePdfRequest) throws ApiException {
    return rotatePdfWithHttpInfo(rotatePdfRequest, null);
  }

  /**
   * Rotate pages of a PDF
   * Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
   * @param rotatePdfRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PdfToolsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PdfToolsResponse> rotatePdfWithHttpInfo(@jakarta.annotation.Nonnull RotatePdfRequest rotatePdfRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = rotatePdfRequestBuilder(rotatePdfRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("rotatePdf", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PdfToolsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PdfToolsResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PdfToolsResponse>() {});
        

        return new ApiResponse<PdfToolsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder rotatePdfRequestBuilder(@jakarta.annotation.Nonnull RotatePdfRequest rotatePdfRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'rotatePdfRequest' is set
    if (rotatePdfRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'rotatePdfRequest' when calling rotatePdf");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/pdf-tools/rotate";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(rotatePdfRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
