/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.S3ConfigRequest;
import com.templatefox.sdk.model.S3ConfigResponse;
import com.templatefox.sdk.model.S3SuccessResponse;
import com.templatefox.sdk.model.S3TestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for IntegrationsApi
 */
@Disabled
public class IntegrationsApiTest {

    private final IntegrationsApi api = new IntegrationsApi();

    
    /**
     * Delete S3 configuration
     *
     * Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteS3ConfigTest() throws ApiException {
        S3SuccessResponse response = 
        api.deleteS3Config();
        
        // TODO: test validations
    }
    
    /**
     * Get S3 configuration
     *
     * Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getS3ConfigTest() throws ApiException {
        S3ConfigResponse response = 
        api.getS3Config();
        
        // TODO: test validations
    }
    
    /**
     * Save S3 configuration
     *
     * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveS3ConfigTest() throws ApiException {
        S3ConfigRequest s3ConfigRequest = null;
        S3SuccessResponse response = 
        api.saveS3Config(s3ConfigRequest);
        
        // TODO: test validations
    }
    
    /**
     * Test S3 connection
     *
     * Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void testS3ConnectionTest() throws ApiException {
        S3TestResponse response = 
        api.testS3Connection();
        
        // TODO: test validations
    }
    
}
