/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.CreateAsyncPdfRequest;
import com.templatefox.sdk.model.CreateAsyncPdfResponse;
import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.JobListResponse;
import com.templatefox.sdk.model.JobStatus;
import com.templatefox.sdk.model.JobStatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PdfAsyncApi
 */
@Disabled
public class PdfAsyncApiTest {

    private final PdfAsyncApi api = new PdfAsyncApi();

    
    /**
     * Generate PDF asynchronously
     *
     * Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPdfAsyncTest() throws ApiException {
        CreateAsyncPdfRequest createAsyncPdfRequest = null;
        CreateAsyncPdfResponse response = 
        api.createPdfAsync(createAsyncPdfRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get PDF job status
     *
     * Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPdfJobStatusTest() throws ApiException {
        String jobId = null;
        JobStatusResponse response = 
        api.getPdfJobStatus(jobId);
        
        // TODO: test validations
    }
    
    /**
     * List PDF jobs
     *
     * List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPdfJobsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        JobStatus status = null;
        JobListResponse response = 
        api.listPdfJobs(limit, offset, status);
        
        // TODO: test validations
    }
    
}
