/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.1.dev2+gfe6303fdd.d20260209
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.CreatePdfRequest;
import com.templatefox.sdk.model.CreatePdfResponse;
import java.io.File;
import com.templatefox.sdk.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PdfApi
 */
@Disabled
public class PdfApiTest {

    private final PdfApi api = new PdfApi();

    
    /**
     * Generate PDF from template
     *
     * Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;data&#x60; | object | ✅ Yes | Key-value data to render in template | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; | | &#x60;expiration&#x60; | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - &#x60;url&#x60; (default): PDF is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPdfTest() throws ApiException {
        CreatePdfRequest createPdfRequest = null;
        CreatePdfResponse response = 
        api.createPdf(createPdfRequest);
        
        // TODO: test validations
    }
    
}
