/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.ExtractPdfPagesRequest;
import com.templatefox.sdk.model.MergePdfRequest;
import com.templatefox.sdk.model.PdfToolsResponse;
import com.templatefox.sdk.model.RotatePdfRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PdfToolsApi
 */
@Disabled
public class PdfToolsApiTest {

    private final PdfToolsApi api = new PdfToolsApi();

    
    /**
     * Extract pages from a PDF
     *
     * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void extractPdfPagesTest() throws ApiException {
        ExtractPdfPagesRequest extractPdfPagesRequest = null;
        PdfToolsResponse response = 
        api.extractPdfPages(extractPdfPagesRequest);
        
        // TODO: test validations
    }
    
    /**
     * Merge PDFs
     *
     * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mergePdfTest() throws ApiException {
        MergePdfRequest mergePdfRequest = null;
        PdfToolsResponse response = 
        api.mergePdf(mergePdfRequest);
        
        // TODO: test validations
    }
    
    /**
     * Rotate pages of a PDF
     *
     * Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rotatePdfTest() throws ApiException {
        RotatePdfRequest rotatePdfRequest = null;
        PdfToolsResponse response = 
        api.rotatePdf(rotatePdfRequest);
        
        // TODO: test validations
    }
    
}
