/*
 * TemplateFox API
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.TemplateField;
import com.templatefox.sdk.model.TemplatesListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for TemplatesApi
 */
@Disabled
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    
    /**
     * Get template fields
     *
     * Get the dynamic fields for a template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for Zapier Dynamic Fields integration. It returns an array of field definitions that Zapier uses to dynamically generate input forms.  **Response format:** Array of objects compatible with Zapier InputFieldsSchema. Each field has: &#x60;key&#x60;, &#x60;label&#x60;, &#x60;type&#x60;, &#x60;required&#x60;, and optional &#x60;helpText&#x60;.  **Field types:** - &#x60;string&#x60;: Text input (also used for JSON arrays/objects) - &#x60;integer&#x60;: Integer number - &#x60;number&#x60;: Decimal number - &#x60;boolean&#x60;: True/False checkbox  **Arrays and objects:** Complex types are returned as &#x60;string&#x60; type with a &#x60;helpText&#x60; showing the expected JSON format.  **No credits consumed:** This is a read-only endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTemplateFieldsTest() throws ApiException {
        String templateId = null;
        List<TemplateField> response = 
        api.getTemplateFields(templateId);
        
        // TODO: test validations
    }
    
    /**
     * List templates
     *
     * List all templates for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTemplatesTest() throws ApiException {
        TemplatesListResponse response = 
        api.listTemplates();
        
        // TODO: test validations
    }
    
}
