/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.api;

import com.templatefox.sdk.ApiException;
import com.templatefox.sdk.model.CreateVersionRequest;
import com.templatefox.sdk.model.HTTPValidationError;
import com.templatefox.sdk.model.SetDefaultVersionRequest;
import com.templatefox.sdk.model.TemplateField;
import com.templatefox.sdk.model.TemplatesListResponse;
import com.templatefox.sdk.model.UpdateVersionRequest;
import com.templatefox.sdk.model.VersionItem;
import com.templatefox.sdk.model.VersionsListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for TemplatesApi
 */
@Disabled
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    
    /**
     * Create a version snapshot
     *
     * Create an immutable snapshot of the current template draft.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTemplateVersionTest() throws ApiException {
        String templateId = null;
        CreateVersionRequest createVersionRequest = null;
        VersionItem response = 
        api.createTemplateVersion(templateId, createVersionRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete a version
     *
     * Delete a specific version snapshot.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTemplateVersionTest() throws ApiException {
        String templateId = null;
        Integer versionNumber = null;
        Object response = 
        api.deleteTemplateVersion(templateId, versionNumber);
        
        // TODO: test validations
    }
    
    /**
     * Get template fields
     *
     * Get the dynamic fields for a template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: &#x60;key&#x60;, &#x60;label&#x60;, &#x60;type&#x60;, &#x60;required&#x60;, optional &#x60;helpText&#x60;, and optional &#x60;spec&#x60; (for array fields).  **Field types:** - &#x60;string&#x60;: Text input - &#x60;integer&#x60;: Integer number - &#x60;number&#x60;: Decimal number - &#x60;boolean&#x60;: True/False checkbox - &#x60;array&#x60;: Array of items with nested &#x60;spec&#x60; defining item structure  **Array fields:** When a field is an array of objects, the response includes a &#x60;spec&#x60; array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTemplateFieldsTest() throws ApiException {
        String templateId = null;
        List<TemplateField> response = 
        api.getTemplateFields(templateId);
        
        // TODO: test validations
    }
    
    /**
     * List template versions
     *
     * List all snapshot versions for a template (excludes the working draft).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTemplateVersionsTest() throws ApiException {
        String templateId = null;
        VersionsListResponse response = 
        api.listTemplateVersions(templateId);
        
        // TODO: test validations
    }
    
    /**
     * List templates
     *
     * List all templates for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTemplatesTest() throws ApiException {
        TemplatesListResponse response = 
        api.listTemplates();
        
        // TODO: test validations
    }
    
    /**
     * Remove default version
     *
     * Remove the default version setting. API will use the working draft.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDefaultVersionTest() throws ApiException {
        String templateId = null;
        Object response = 
        api.removeDefaultVersion(templateId);
        
        // TODO: test validations
    }
    
    /**
     * Set default version
     *
     * Set which version the API uses by default when no version param is provided.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setDefaultVersionTest() throws ApiException {
        String templateId = null;
        SetDefaultVersionRequest setDefaultVersionRequest = null;
        Object response = 
        api.setDefaultVersion(templateId, setDefaultVersionRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update a version
     *
     * Update a version&#39;s tag or description.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTemplateVersionTest() throws ApiException {
        String templateId = null;
        Integer versionNumber = null;
        UpdateVersionRequest updateVersionRequest = null;
        VersionItem response = 
        api.updateTemplateVersion(templateId, versionNumber, updateVersionRequest);
        
        // TODO: test validations
    }
    
}
