/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.AppRoutersV1PdfExportType;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Request model for PDF generation
 */
@JsonPropertyOrder({
  CreatePdfRequest.JSON_PROPERTY_TEMPLATE_ID,
  CreatePdfRequest.JSON_PROPERTY_DATA,
  CreatePdfRequest.JSON_PROPERTY_EXPORT_TYPE,
  CreatePdfRequest.JSON_PROPERTY_EXPIRATION,
  CreatePdfRequest.JSON_PROPERTY_FILENAME,
  CreatePdfRequest.JSON_PROPERTY_STORE_S3,
  CreatePdfRequest.JSON_PROPERTY_S3_FILEPATH,
  CreatePdfRequest.JSON_PROPERTY_S3_BUCKET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class CreatePdfRequest {
  public static final String JSON_PROPERTY_TEMPLATE_ID = "template_id";
  @jakarta.annotation.Nonnull
  private String templateId;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nonnull
  private Map<String, Object> data = new HashMap<>();

  public static final String JSON_PROPERTY_EXPORT_TYPE = "export_type";
  @jakarta.annotation.Nullable
  private AppRoutersV1PdfExportType exportType = AppRoutersV1PdfExportType.URL;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @jakarta.annotation.Nullable
  private Integer expiration = 86400;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STORE_S3 = "store_s3";
  @jakarta.annotation.Nullable
  private Boolean storeS3 = false;

  public static final String JSON_PROPERTY_S3_FILEPATH = "s3_filepath";
  private JsonNullable<String> s3Filepath = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_S3_BUCKET = "s3_bucket";
  private JsonNullable<String> s3Bucket = JsonNullable.<String>undefined();

  public CreatePdfRequest() { 
  }

  public CreatePdfRequest templateId(@jakarta.annotation.Nonnull String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * **Required.** Template short ID (12 characters)
   * @return templateId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplateId() {
    return templateId;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplateId(@jakarta.annotation.Nonnull String templateId) {
    this.templateId = templateId;
  }


  public CreatePdfRequest data(@jakarta.annotation.Nonnull Map<String, Object> data) {
    this.data = data;
    return this;
  }

  public CreatePdfRequest putDataItem(String key, Object dataItem) {
    if (this.data == null) {
      this.data = new HashMap<>();
    }
    this.data.put(key, dataItem);
    return this;
  }

  /**
   * **Required.** Key-value data to render in the template. Keys must match template variables.
   * @return data
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setData(@jakarta.annotation.Nonnull Map<String, Object> data) {
    this.data = data;
  }


  public CreatePdfRequest exportType(@jakarta.annotation.Nullable AppRoutersV1PdfExportType exportType) {
    this.exportType = exportType;
    return this;
  }

  /**
   * Export format: &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes
   * @return exportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AppRoutersV1PdfExportType getExportType() {
    return exportType;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportType(@jakarta.annotation.Nullable AppRoutersV1PdfExportType exportType) {
    this.exportType = exportType;
  }


  public CreatePdfRequest expiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to &#x60;url&#x60; export type.
   * minimum: 60
   * maximum: 604800
   * @return expiration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExpiration() {
    return expiration;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
  }


  public CreatePdfRequest filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }


  public CreatePdfRequest storeS3(@jakarta.annotation.Nullable Boolean storeS3) {
    this.storeS3 = storeS3;
    return this;
  }

  /**
   * Upload to your configured S3 bucket instead of CDN
   * @return storeS3
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STORE_S3, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getStoreS3() {
    return storeS3;
  }


  @JsonProperty(value = JSON_PROPERTY_STORE_S3, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoreS3(@jakarta.annotation.Nullable Boolean storeS3) {
    this.storeS3 = storeS3;
  }


  public CreatePdfRequest s3Filepath(@jakarta.annotation.Nullable String s3Filepath) {
    this.s3Filepath = JsonNullable.<String>of(s3Filepath);
    return this;
  }

  /**
   * Get s3Filepath
   * @return s3Filepath
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getS3Filepath() {
        return s3Filepath.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_S3_FILEPATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getS3Filepath_JsonNullable() {
    return s3Filepath;
  }
  
  @JsonProperty(JSON_PROPERTY_S3_FILEPATH)
  public void setS3Filepath_JsonNullable(JsonNullable<String> s3Filepath) {
    this.s3Filepath = s3Filepath;
  }

  public void setS3Filepath(@jakarta.annotation.Nullable String s3Filepath) {
    this.s3Filepath = JsonNullable.<String>of(s3Filepath);
  }


  public CreatePdfRequest s3Bucket(@jakarta.annotation.Nullable String s3Bucket) {
    this.s3Bucket = JsonNullable.<String>of(s3Bucket);
    return this;
  }

  /**
   * Get s3Bucket
   * @return s3Bucket
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getS3Bucket() {
        return s3Bucket.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_S3_BUCKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getS3Bucket_JsonNullable() {
    return s3Bucket;
  }
  
  @JsonProperty(JSON_PROPERTY_S3_BUCKET)
  public void setS3Bucket_JsonNullable(JsonNullable<String> s3Bucket) {
    this.s3Bucket = s3Bucket;
  }

  public void setS3Bucket(@jakarta.annotation.Nullable String s3Bucket) {
    this.s3Bucket = JsonNullable.<String>of(s3Bucket);
  }


  /**
   * Return true if this CreatePdfRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePdfRequest createPdfRequest = (CreatePdfRequest) o;
    return Objects.equals(this.templateId, createPdfRequest.templateId) &&
        Objects.equals(this.data, createPdfRequest.data) &&
        Objects.equals(this.exportType, createPdfRequest.exportType) &&
        Objects.equals(this.expiration, createPdfRequest.expiration) &&
        equalsNullable(this.filename, createPdfRequest.filename) &&
        Objects.equals(this.storeS3, createPdfRequest.storeS3) &&
        equalsNullable(this.s3Filepath, createPdfRequest.s3Filepath) &&
        equalsNullable(this.s3Bucket, createPdfRequest.s3Bucket);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, data, exportType, expiration, hashCodeNullable(filename), storeS3, hashCodeNullable(s3Filepath), hashCodeNullable(s3Bucket));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePdfRequest {\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    exportType: ").append(toIndentedString(exportType)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    storeS3: ").append(toIndentedString(storeS3)).append("\n");
    sb.append("    s3Filepath: ").append(toIndentedString(s3Filepath)).append("\n");
    sb.append("    s3Bucket: ").append(toIndentedString(s3Bucket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `template_id` to the URL query string
    if (getTemplateId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateId()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (String _key : getData().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdata%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getData().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getData().get(_key)))));
      }
    }

    // add `export_type` to the URL query string
    if (getExportType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexport_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExportType()))));
    }

    // add `expiration` to the URL query string
    if (getExpiration() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiration()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `store_s3` to the URL query string
    if (getStoreS3() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstore_s3%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStoreS3()))));
    }

    // add `s3_filepath` to the URL query string
    if (getS3Filepath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ss3_filepath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getS3Filepath()))));
    }

    // add `s3_bucket` to the URL query string
    if (getS3Bucket() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ss3_bucket%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getS3Bucket()))));
    }

    return joiner.toString();
  }
}

