/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for URL export type
 */
@JsonPropertyOrder({
  CreatePdfResponse.JSON_PROPERTY_URL,
  CreatePdfResponse.JSON_PROPERTY_FILENAME,
  CreatePdfResponse.JSON_PROPERTY_CREDITS_REMAINING,
  CreatePdfResponse.JSON_PROPERTY_EXPIRES_IN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class CreatePdfResponse {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @jakarta.annotation.Nonnull
  private String filename;

  public static final String JSON_PROPERTY_CREDITS_REMAINING = "credits_remaining";
  @jakarta.annotation.Nonnull
  private Integer creditsRemaining;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @jakarta.annotation.Nonnull
  private Integer expiresIn;

  public CreatePdfResponse() { 
  }

  public CreatePdfResponse url(@jakarta.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Signed URL to download the PDF (expires after specified time)
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }


  public CreatePdfResponse filename(@jakarta.annotation.Nonnull String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Filename of the generated PDF
   * @return filename
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFilename() {
    return filename;
  }


  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilename(@jakarta.annotation.Nonnull String filename) {
    this.filename = filename;
  }


  public CreatePdfResponse creditsRemaining(@jakarta.annotation.Nonnull Integer creditsRemaining) {
    this.creditsRemaining = creditsRemaining;
    return this;
  }

  /**
   * Remaining credits after this request
   * @return creditsRemaining
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDITS_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCreditsRemaining() {
    return creditsRemaining;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDITS_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditsRemaining(@jakarta.annotation.Nonnull Integer creditsRemaining) {
    this.creditsRemaining = creditsRemaining;
  }


  public CreatePdfResponse expiresIn(@jakarta.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Seconds until URL expires
   * @return expiresIn
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresIn(@jakarta.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  /**
   * Return true if this CreatePdfResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePdfResponse createPdfResponse = (CreatePdfResponse) o;
    return Objects.equals(this.url, createPdfResponse.url) &&
        Objects.equals(this.filename, createPdfResponse.filename) &&
        Objects.equals(this.creditsRemaining, createPdfResponse.creditsRemaining) &&
        Objects.equals(this.expiresIn, createPdfResponse.expiresIn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, filename, creditsRemaining, expiresIn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePdfResponse {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    creditsRemaining: ").append(toIndentedString(creditsRemaining)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `credits_remaining` to the URL query string
    if (getCreditsRemaining() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scredits_remaining%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreditsRemaining()))));
    }

    // add `expires_in` to the URL query string
    if (getExpiresIn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires_in%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresIn()))));
    }

    return joiner.toString();
  }
}

