/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.JobStatus;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for async PDF creation
 */
@JsonPropertyOrder({
  CreateAsyncPdfResponse.JSON_PROPERTY_JOB_ID,
  CreateAsyncPdfResponse.JSON_PROPERTY_STATUS,
  CreateAsyncPdfResponse.JSON_PROPERTY_CREDITS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class CreateAsyncPdfResponse {
  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  @jakarta.annotation.Nonnull
  private String jobId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private JobStatus status;

  public static final String JSON_PROPERTY_CREDITS_REMAINING = "credits_remaining";
  @jakarta.annotation.Nonnull
  private Integer creditsRemaining;

  public CreateAsyncPdfResponse() { 
  }

  public CreateAsyncPdfResponse jobId(@jakarta.annotation.Nonnull String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Unique job identifier for status polling
   * @return jobId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getJobId() {
    return jobId;
  }


  @JsonProperty(value = JSON_PROPERTY_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJobId(@jakarta.annotation.Nonnull String jobId) {
    this.jobId = jobId;
  }


  public CreateAsyncPdfResponse status(@jakarta.annotation.Nonnull JobStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Initial job status (always &#39;pending&#39;)
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public JobStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull JobStatus status) {
    this.status = status;
  }


  public CreateAsyncPdfResponse creditsRemaining(@jakarta.annotation.Nonnull Integer creditsRemaining) {
    this.creditsRemaining = creditsRemaining;
    return this;
  }

  /**
   * Remaining credits after this request
   * @return creditsRemaining
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDITS_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCreditsRemaining() {
    return creditsRemaining;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDITS_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditsRemaining(@jakarta.annotation.Nonnull Integer creditsRemaining) {
    this.creditsRemaining = creditsRemaining;
  }


  /**
   * Return true if this CreateAsyncPdfResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAsyncPdfResponse createAsyncPdfResponse = (CreateAsyncPdfResponse) o;
    return Objects.equals(this.jobId, createAsyncPdfResponse.jobId) &&
        Objects.equals(this.status, createAsyncPdfResponse.status) &&
        Objects.equals(this.creditsRemaining, createAsyncPdfResponse.creditsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, status, creditsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAsyncPdfResponse {\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creditsRemaining: ").append(toIndentedString(creditsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `job_id` to the URL query string
    if (getJobId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sjob_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getJobId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `credits_remaining` to the URL query string
    if (getCreditsRemaining() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scredits_remaining%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreditsRemaining()))));
    }

    return joiner.toString();
  }
}

