/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.JobStatusResponse;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for job list query
 */
@JsonPropertyOrder({
  JobListResponse.JSON_PROPERTY_JOBS,
  JobListResponse.JSON_PROPERTY_TOTAL,
  JobListResponse.JSON_PROPERTY_LIMIT,
  JobListResponse.JSON_PROPERTY_OFFSET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class JobListResponse {
  public static final String JSON_PROPERTY_JOBS = "jobs";
  @jakarta.annotation.Nonnull
  private List<JobStatusResponse> jobs = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL = "total";
  @jakarta.annotation.Nonnull
  private Integer total;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  @jakarta.annotation.Nonnull
  private Integer offset;

  public JobListResponse() { 
  }

  public JobListResponse jobs(@jakarta.annotation.Nonnull List<JobStatusResponse> jobs) {
    this.jobs = jobs;
    return this;
  }

  public JobListResponse addJobsItem(JobStatusResponse jobsItem) {
    if (this.jobs == null) {
      this.jobs = new ArrayList<>();
    }
    this.jobs.add(jobsItem);
    return this;
  }

  /**
   * List of jobs
   * @return jobs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_JOBS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<JobStatusResponse> getJobs() {
    return jobs;
  }


  @JsonProperty(value = JSON_PROPERTY_JOBS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJobs(@jakarta.annotation.Nonnull List<JobStatusResponse> jobs) {
    this.jobs = jobs;
  }


  public JobListResponse total(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Total number of jobs matching filter
   * @return total
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
  }


  public JobListResponse limit(@jakarta.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Page size
   * @return limit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@jakarta.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public JobListResponse offset(@jakarta.annotation.Nonnull Integer offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Page offset
   * @return offset
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getOffset() {
    return offset;
  }


  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOffset(@jakarta.annotation.Nonnull Integer offset) {
    this.offset = offset;
  }


  /**
   * Return true if this JobListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobListResponse jobListResponse = (JobListResponse) o;
    return Objects.equals(this.jobs, jobListResponse.jobs) &&
        Objects.equals(this.total, jobListResponse.total) &&
        Objects.equals(this.limit, jobListResponse.limit) &&
        Objects.equals(this.offset, jobListResponse.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobs, total, limit, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobListResponse {\n");
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `jobs` to the URL query string
    if (getJobs() != null) {
      for (int i = 0; i < getJobs().size(); i++) {
        if (getJobs().get(i) != null) {
          joiner.add(getJobs().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sjobs%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `offset` to the URL query string
    if (getOffset() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soffset%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOffset()))));
    }

    return joiner.toString();
  }
}

