/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.JobStatus;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for job status query
 */
@JsonPropertyOrder({
  JobStatusResponse.JSON_PROPERTY_ID,
  JobStatusResponse.JSON_PROPERTY_STATUS,
  JobStatusResponse.JSON_PROPERTY_TEMPLATE_ID,
  JobStatusResponse.JSON_PROPERTY_EXPORT_TYPE,
  JobStatusResponse.JSON_PROPERTY_FILENAME,
  JobStatusResponse.JSON_PROPERTY_STORE_S3,
  JobStatusResponse.JSON_PROPERTY_CREATED_AT,
  JobStatusResponse.JSON_PROPERTY_UPDATED_AT,
  JobStatusResponse.JSON_PROPERTY_COMPLETED_AT,
  JobStatusResponse.JSON_PROPERTY_RESULT_URL,
  JobStatusResponse.JSON_PROPERTY_RESULT_FILENAME,
  JobStatusResponse.JSON_PROPERTY_RESULT_EXPIRES_AT,
  JobStatusResponse.JSON_PROPERTY_RESULT_S3_BUCKET,
  JobStatusResponse.JSON_PROPERTY_RESULT_S3_KEY,
  JobStatusResponse.JSON_PROPERTY_ERROR_MESSAGE,
  JobStatusResponse.JSON_PROPERTY_ERROR_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class JobStatusResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private JobStatus status;

  public static final String JSON_PROPERTY_TEMPLATE_ID = "template_id";
  @jakarta.annotation.Nonnull
  private String templateId;

  public static final String JSON_PROPERTY_EXPORT_TYPE = "export_type";
  @jakarta.annotation.Nonnull
  private String exportType;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STORE_S3 = "store_s3";
  @jakarta.annotation.Nonnull
  private Boolean storeS3;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nonnull
  private String updatedAt;

  public static final String JSON_PROPERTY_COMPLETED_AT = "completed_at";
  private JsonNullable<String> completedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESULT_URL = "result_url";
  private JsonNullable<String> resultUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESULT_FILENAME = "result_filename";
  private JsonNullable<String> resultFilename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESULT_EXPIRES_AT = "result_expires_at";
  private JsonNullable<String> resultExpiresAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESULT_S3_BUCKET = "result_s3_bucket";
  private JsonNullable<String> resultS3Bucket = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESULT_S3_KEY = "result_s3_key";
  private JsonNullable<String> resultS3Key = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "error_message";
  private JsonNullable<String> errorMessage = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ERROR_CODE = "error_code";
  private JsonNullable<String> errorCode = JsonNullable.<String>undefined();

  public JobStatusResponse() { 
  }

  public JobStatusResponse id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Job ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public JobStatusResponse status(@jakarta.annotation.Nonnull JobStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Current job status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public JobStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull JobStatus status) {
    this.status = status;
  }


  public JobStatusResponse templateId(@jakarta.annotation.Nonnull String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * Template used for generation
   * @return templateId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplateId() {
    return templateId;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplateId(@jakarta.annotation.Nonnull String templateId) {
    this.templateId = templateId;
  }


  public JobStatusResponse exportType(@jakarta.annotation.Nonnull String exportType) {
    this.exportType = exportType;
    return this;
  }

  /**
   * Export type (url)
   * @return exportType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExportType() {
    return exportType;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExportType(@jakarta.annotation.Nonnull String exportType) {
    this.exportType = exportType;
  }


  public JobStatusResponse filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }


  public JobStatusResponse storeS3(@jakarta.annotation.Nonnull Boolean storeS3) {
    this.storeS3 = storeS3;
    return this;
  }

  /**
   * Whether S3 storage was requested
   * @return storeS3
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STORE_S3, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getStoreS3() {
    return storeS3;
  }


  @JsonProperty(value = JSON_PROPERTY_STORE_S3, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStoreS3(@jakarta.annotation.Nonnull Boolean storeS3) {
    this.storeS3 = storeS3;
  }


  public JobStatusResponse createdAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Job creation timestamp (ISO 8601)
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public JobStatusResponse updatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp (ISO 8601)
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public JobStatusResponse completedAt(@jakarta.annotation.Nullable String completedAt) {
    this.completedAt = JsonNullable.<String>of(completedAt);
    return this;
  }

  /**
   * Get completedAt
   * @return completedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getCompletedAt() {
        return completedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COMPLETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCompletedAt_JsonNullable() {
    return completedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETED_AT)
  public void setCompletedAt_JsonNullable(JsonNullable<String> completedAt) {
    this.completedAt = completedAt;
  }

  public void setCompletedAt(@jakarta.annotation.Nullable String completedAt) {
    this.completedAt = JsonNullable.<String>of(completedAt);
  }


  public JobStatusResponse resultUrl(@jakarta.annotation.Nullable String resultUrl) {
    this.resultUrl = JsonNullable.<String>of(resultUrl);
    return this;
  }

  /**
   * Get resultUrl
   * @return resultUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getResultUrl() {
        return resultUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESULT_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResultUrl_JsonNullable() {
    return resultUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULT_URL)
  public void setResultUrl_JsonNullable(JsonNullable<String> resultUrl) {
    this.resultUrl = resultUrl;
  }

  public void setResultUrl(@jakarta.annotation.Nullable String resultUrl) {
    this.resultUrl = JsonNullable.<String>of(resultUrl);
  }


  public JobStatusResponse resultFilename(@jakarta.annotation.Nullable String resultFilename) {
    this.resultFilename = JsonNullable.<String>of(resultFilename);
    return this;
  }

  /**
   * Get resultFilename
   * @return resultFilename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getResultFilename() {
        return resultFilename.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESULT_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResultFilename_JsonNullable() {
    return resultFilename;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULT_FILENAME)
  public void setResultFilename_JsonNullable(JsonNullable<String> resultFilename) {
    this.resultFilename = resultFilename;
  }

  public void setResultFilename(@jakarta.annotation.Nullable String resultFilename) {
    this.resultFilename = JsonNullable.<String>of(resultFilename);
  }


  public JobStatusResponse resultExpiresAt(@jakarta.annotation.Nullable String resultExpiresAt) {
    this.resultExpiresAt = JsonNullable.<String>of(resultExpiresAt);
    return this;
  }

  /**
   * Get resultExpiresAt
   * @return resultExpiresAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getResultExpiresAt() {
        return resultExpiresAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESULT_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResultExpiresAt_JsonNullable() {
    return resultExpiresAt;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULT_EXPIRES_AT)
  public void setResultExpiresAt_JsonNullable(JsonNullable<String> resultExpiresAt) {
    this.resultExpiresAt = resultExpiresAt;
  }

  public void setResultExpiresAt(@jakarta.annotation.Nullable String resultExpiresAt) {
    this.resultExpiresAt = JsonNullable.<String>of(resultExpiresAt);
  }


  public JobStatusResponse resultS3Bucket(@jakarta.annotation.Nullable String resultS3Bucket) {
    this.resultS3Bucket = JsonNullable.<String>of(resultS3Bucket);
    return this;
  }

  /**
   * Get resultS3Bucket
   * @return resultS3Bucket
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getResultS3Bucket() {
        return resultS3Bucket.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESULT_S3_BUCKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResultS3Bucket_JsonNullable() {
    return resultS3Bucket;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULT_S3_BUCKET)
  public void setResultS3Bucket_JsonNullable(JsonNullable<String> resultS3Bucket) {
    this.resultS3Bucket = resultS3Bucket;
  }

  public void setResultS3Bucket(@jakarta.annotation.Nullable String resultS3Bucket) {
    this.resultS3Bucket = JsonNullable.<String>of(resultS3Bucket);
  }


  public JobStatusResponse resultS3Key(@jakarta.annotation.Nullable String resultS3Key) {
    this.resultS3Key = JsonNullable.<String>of(resultS3Key);
    return this;
  }

  /**
   * Get resultS3Key
   * @return resultS3Key
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getResultS3Key() {
        return resultS3Key.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESULT_S3_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResultS3Key_JsonNullable() {
    return resultS3Key;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULT_S3_KEY)
  public void setResultS3Key_JsonNullable(JsonNullable<String> resultS3Key) {
    this.resultS3Key = resultS3Key;
  }

  public void setResultS3Key(@jakarta.annotation.Nullable String resultS3Key) {
    this.resultS3Key = JsonNullable.<String>of(resultS3Key);
  }


  public JobStatusResponse errorMessage(@jakarta.annotation.Nullable String errorMessage) {
    this.errorMessage = JsonNullable.<String>of(errorMessage);
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getErrorMessage() {
        return errorMessage.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ERROR_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getErrorMessage_JsonNullable() {
    return errorMessage;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  public void setErrorMessage_JsonNullable(JsonNullable<String> errorMessage) {
    this.errorMessage = errorMessage;
  }

  public void setErrorMessage(@jakarta.annotation.Nullable String errorMessage) {
    this.errorMessage = JsonNullable.<String>of(errorMessage);
  }


  public JobStatusResponse errorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = JsonNullable.<String>of(errorCode);
    return this;
  }

  /**
   * Get errorCode
   * @return errorCode
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getErrorCode() {
        return errorCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ERROR_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getErrorCode_JsonNullable() {
    return errorCode;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  public void setErrorCode_JsonNullable(JsonNullable<String> errorCode) {
    this.errorCode = errorCode;
  }

  public void setErrorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = JsonNullable.<String>of(errorCode);
  }


  /**
   * Return true if this JobStatusResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobStatusResponse jobStatusResponse = (JobStatusResponse) o;
    return Objects.equals(this.id, jobStatusResponse.id) &&
        Objects.equals(this.status, jobStatusResponse.status) &&
        Objects.equals(this.templateId, jobStatusResponse.templateId) &&
        Objects.equals(this.exportType, jobStatusResponse.exportType) &&
        equalsNullable(this.filename, jobStatusResponse.filename) &&
        Objects.equals(this.storeS3, jobStatusResponse.storeS3) &&
        Objects.equals(this.createdAt, jobStatusResponse.createdAt) &&
        Objects.equals(this.updatedAt, jobStatusResponse.updatedAt) &&
        equalsNullable(this.completedAt, jobStatusResponse.completedAt) &&
        equalsNullable(this.resultUrl, jobStatusResponse.resultUrl) &&
        equalsNullable(this.resultFilename, jobStatusResponse.resultFilename) &&
        equalsNullable(this.resultExpiresAt, jobStatusResponse.resultExpiresAt) &&
        equalsNullable(this.resultS3Bucket, jobStatusResponse.resultS3Bucket) &&
        equalsNullable(this.resultS3Key, jobStatusResponse.resultS3Key) &&
        equalsNullable(this.errorMessage, jobStatusResponse.errorMessage) &&
        equalsNullable(this.errorCode, jobStatusResponse.errorCode);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, templateId, exportType, hashCodeNullable(filename), storeS3, createdAt, updatedAt, hashCodeNullable(completedAt), hashCodeNullable(resultUrl), hashCodeNullable(resultFilename), hashCodeNullable(resultExpiresAt), hashCodeNullable(resultS3Bucket), hashCodeNullable(resultS3Key), hashCodeNullable(errorMessage), hashCodeNullable(errorCode));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobStatusResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    exportType: ").append(toIndentedString(exportType)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    storeS3: ").append(toIndentedString(storeS3)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    resultUrl: ").append(toIndentedString(resultUrl)).append("\n");
    sb.append("    resultFilename: ").append(toIndentedString(resultFilename)).append("\n");
    sb.append("    resultExpiresAt: ").append(toIndentedString(resultExpiresAt)).append("\n");
    sb.append("    resultS3Bucket: ").append(toIndentedString(resultS3Bucket)).append("\n");
    sb.append("    resultS3Key: ").append(toIndentedString(resultS3Key)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `template_id` to the URL query string
    if (getTemplateId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateId()))));
    }

    // add `export_type` to the URL query string
    if (getExportType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexport_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExportType()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `store_s3` to the URL query string
    if (getStoreS3() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstore_s3%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStoreS3()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `completed_at` to the URL query string
    if (getCompletedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompleted_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompletedAt()))));
    }

    // add `result_url` to the URL query string
    if (getResultUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResultUrl()))));
    }

    // add `result_filename` to the URL query string
    if (getResultFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult_filename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResultFilename()))));
    }

    // add `result_expires_at` to the URL query string
    if (getResultExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult_expires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResultExpiresAt()))));
    }

    // add `result_s3_bucket` to the URL query string
    if (getResultS3Bucket() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult_s3_bucket%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResultS3Bucket()))));
    }

    // add `result_s3_key` to the URL query string
    if (getResultS3Key() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresult_s3_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResultS3Key()))));
    }

    // add `error_message` to the URL query string
    if (getErrorMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror_message%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorMessage()))));
    }

    // add `error_code` to the URL query string
    if (getErrorCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorCode()))));
    }

    return joiner.toString();
  }
}

