/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.AppRoutersV1PdfToolsExportType;
import com.templatefox.sdk.model.PdfInput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * MergePdfRequest
 */
@JsonPropertyOrder({
  MergePdfRequest.JSON_PROPERTY_EXPORT_TYPE,
  MergePdfRequest.JSON_PROPERTY_EXPIRATION,
  MergePdfRequest.JSON_PROPERTY_FILENAME,
  MergePdfRequest.JSON_PROPERTY_PDFS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MergePdfRequest {
  public static final String JSON_PROPERTY_EXPORT_TYPE = "export_type";
  @jakarta.annotation.Nullable
  private AppRoutersV1PdfToolsExportType exportType = AppRoutersV1PdfToolsExportType.URL;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @jakarta.annotation.Nullable
  private Integer expiration = 86400;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PDFS = "pdfs";
  @jakarta.annotation.Nonnull
  private List<PdfInput> pdfs = new ArrayList<>();

  public MergePdfRequest() { 
  }

  public MergePdfRequest exportType(@jakarta.annotation.Nullable AppRoutersV1PdfToolsExportType exportType) {
    this.exportType = exportType;
    return this;
  }

  /**
   * &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes
   * @return exportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AppRoutersV1PdfToolsExportType getExportType() {
    return exportType;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportType(@jakarta.annotation.Nullable AppRoutersV1PdfToolsExportType exportType) {
    this.exportType = exportType;
  }


  public MergePdfRequest expiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.
   * minimum: 60
   * maximum: 604800
   * @return expiration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExpiration() {
    return expiration;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
  }


  public MergePdfRequest filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }


  public MergePdfRequest pdfs(@jakarta.annotation.Nonnull List<PdfInput> pdfs) {
    this.pdfs = pdfs;
    return this;
  }

  public MergePdfRequest addPdfsItem(PdfInput pdfsItem) {
    if (this.pdfs == null) {
      this.pdfs = new ArrayList<>();
    }
    this.pdfs.add(pdfsItem);
    return this;
  }

  /**
   * Ordered list of PDFs to merge. Each entry has either &#x60;pdf_url&#x60; or &#x60;pdf_base64&#x60;. Minimum 2.
   * @return pdfs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PDFS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<PdfInput> getPdfs() {
    return pdfs;
  }


  @JsonProperty(value = JSON_PROPERTY_PDFS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPdfs(@jakarta.annotation.Nonnull List<PdfInput> pdfs) {
    this.pdfs = pdfs;
  }


  /**
   * Return true if this MergePdfRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergePdfRequest mergePdfRequest = (MergePdfRequest) o;
    return Objects.equals(this.exportType, mergePdfRequest.exportType) &&
        Objects.equals(this.expiration, mergePdfRequest.expiration) &&
        equalsNullable(this.filename, mergePdfRequest.filename) &&
        Objects.equals(this.pdfs, mergePdfRequest.pdfs);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportType, expiration, hashCodeNullable(filename), pdfs);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergePdfRequest {\n");
    sb.append("    exportType: ").append(toIndentedString(exportType)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    pdfs: ").append(toIndentedString(pdfs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `export_type` to the URL query string
    if (getExportType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexport_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExportType()))));
    }

    // add `expiration` to the URL query string
    if (getExpiration() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiration()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `pdfs` to the URL query string
    if (getPdfs() != null) {
      for (int i = 0; i < getPdfs().size(); i++) {
        if (getPdfs().get(i) != null) {
          joiner.add(getPdfs().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spdfs%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

