/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Either pdf_url (HTTPS) or pdf_base64 — exactly one.
 */
@JsonPropertyOrder({
  PdfInput.JSON_PROPERTY_PDF_URL,
  PdfInput.JSON_PROPERTY_PDF_BASE64
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PdfInput {
  public static final String JSON_PROPERTY_PDF_URL = "pdf_url";
  private JsonNullable<String> pdfUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PDF_BASE64 = "pdf_base64";
  private JsonNullable<String> pdfBase64 = JsonNullable.<String>undefined();

  public PdfInput() { 
  }

  public PdfInput pdfUrl(@jakarta.annotation.Nullable String pdfUrl) {
    this.pdfUrl = JsonNullable.<String>of(pdfUrl);
    return this;
  }

  /**
   * Get pdfUrl
   * @return pdfUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPdfUrl() {
        return pdfUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PDF_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPdfUrl_JsonNullable() {
    return pdfUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_PDF_URL)
  public void setPdfUrl_JsonNullable(JsonNullable<String> pdfUrl) {
    this.pdfUrl = pdfUrl;
  }

  public void setPdfUrl(@jakarta.annotation.Nullable String pdfUrl) {
    this.pdfUrl = JsonNullable.<String>of(pdfUrl);
  }


  public PdfInput pdfBase64(@jakarta.annotation.Nullable String pdfBase64) {
    this.pdfBase64 = JsonNullable.<String>of(pdfBase64);
    return this;
  }

  /**
   * Get pdfBase64
   * @return pdfBase64
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPdfBase64() {
        return pdfBase64.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PDF_BASE64, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPdfBase64_JsonNullable() {
    return pdfBase64;
  }
  
  @JsonProperty(JSON_PROPERTY_PDF_BASE64)
  public void setPdfBase64_JsonNullable(JsonNullable<String> pdfBase64) {
    this.pdfBase64 = pdfBase64;
  }

  public void setPdfBase64(@jakarta.annotation.Nullable String pdfBase64) {
    this.pdfBase64 = JsonNullable.<String>of(pdfBase64);
  }


  /**
   * Return true if this PdfInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfInput pdfInput = (PdfInput) o;
    return equalsNullable(this.pdfUrl, pdfInput.pdfUrl) &&
        equalsNullable(this.pdfBase64, pdfInput.pdfBase64);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(pdfUrl), hashCodeNullable(pdfBase64));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfInput {\n");
    sb.append("    pdfUrl: ").append(toIndentedString(pdfUrl)).append("\n");
    sb.append("    pdfBase64: ").append(toIndentedString(pdfBase64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pdf_url` to the URL query string
    if (getPdfUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spdf_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPdfUrl()))));
    }

    // add `pdf_base64` to the URL query string
    if (getPdfBase64() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spdf_base64%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPdfBase64()))));
    }

    return joiner.toString();
  }
}

