/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.AppRoutersV1PdfToolsExportType;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * RotatePdfRequest
 */
@JsonPropertyOrder({
  RotatePdfRequest.JSON_PROPERTY_EXPORT_TYPE,
  RotatePdfRequest.JSON_PROPERTY_EXPIRATION,
  RotatePdfRequest.JSON_PROPERTY_FILENAME,
  RotatePdfRequest.JSON_PROPERTY_PDF_URL,
  RotatePdfRequest.JSON_PROPERTY_PDF_BASE64,
  RotatePdfRequest.JSON_PROPERTY_ROTATION,
  RotatePdfRequest.JSON_PROPERTY_PAGE_ROTATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class RotatePdfRequest {
  public static final String JSON_PROPERTY_EXPORT_TYPE = "export_type";
  @jakarta.annotation.Nullable
  private AppRoutersV1PdfToolsExportType exportType = AppRoutersV1PdfToolsExportType.URL;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  @jakarta.annotation.Nullable
  private Integer expiration = 86400;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PDF_URL = "pdf_url";
  private JsonNullable<String> pdfUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PDF_BASE64 = "pdf_base64";
  private JsonNullable<String> pdfBase64 = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ROTATION = "rotation";
  private JsonNullable<Integer> rotation = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PAGE_ROTATIONS = "page_rotations";
  private JsonNullable<Map<String, Integer>> pageRotations = JsonNullable.<Map<String, Integer>>undefined();

  public RotatePdfRequest() { 
  }

  public RotatePdfRequest exportType(@jakarta.annotation.Nullable AppRoutersV1PdfToolsExportType exportType) {
    this.exportType = exportType;
    return this;
  }

  /**
   * &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes
   * @return exportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AppRoutersV1PdfToolsExportType getExportType() {
    return exportType;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportType(@jakarta.annotation.Nullable AppRoutersV1PdfToolsExportType exportType) {
    this.exportType = exportType;
  }


  public RotatePdfRequest expiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.
   * minimum: 60
   * maximum: 604800
   * @return expiration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExpiration() {
    return expiration;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiration(@jakarta.annotation.Nullable Integer expiration) {
    this.expiration = expiration;
  }


  public RotatePdfRequest filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }


  public RotatePdfRequest pdfUrl(@jakarta.annotation.Nullable String pdfUrl) {
    this.pdfUrl = JsonNullable.<String>of(pdfUrl);
    return this;
  }

  /**
   * Get pdfUrl
   * @return pdfUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPdfUrl() {
        return pdfUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PDF_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPdfUrl_JsonNullable() {
    return pdfUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_PDF_URL)
  public void setPdfUrl_JsonNullable(JsonNullable<String> pdfUrl) {
    this.pdfUrl = pdfUrl;
  }

  public void setPdfUrl(@jakarta.annotation.Nullable String pdfUrl) {
    this.pdfUrl = JsonNullable.<String>of(pdfUrl);
  }


  public RotatePdfRequest pdfBase64(@jakarta.annotation.Nullable String pdfBase64) {
    this.pdfBase64 = JsonNullable.<String>of(pdfBase64);
    return this;
  }

  /**
   * Get pdfBase64
   * @return pdfBase64
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPdfBase64() {
        return pdfBase64.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PDF_BASE64, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPdfBase64_JsonNullable() {
    return pdfBase64;
  }
  
  @JsonProperty(JSON_PROPERTY_PDF_BASE64)
  public void setPdfBase64_JsonNullable(JsonNullable<String> pdfBase64) {
    this.pdfBase64 = pdfBase64;
  }

  public void setPdfBase64(@jakarta.annotation.Nullable String pdfBase64) {
    this.pdfBase64 = JsonNullable.<String>of(pdfBase64);
  }


  public RotatePdfRequest rotation(@jakarta.annotation.Nullable Integer rotation) {
    this.rotation = JsonNullable.<Integer>of(rotation);
    return this;
  }

  /**
   * Get rotation
   * @return rotation
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getRotation() {
        return rotation.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ROTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getRotation_JsonNullable() {
    return rotation;
  }
  
  @JsonProperty(JSON_PROPERTY_ROTATION)
  public void setRotation_JsonNullable(JsonNullable<Integer> rotation) {
    this.rotation = rotation;
  }

  public void setRotation(@jakarta.annotation.Nullable Integer rotation) {
    this.rotation = JsonNullable.<Integer>of(rotation);
  }


  public RotatePdfRequest pageRotations(@jakarta.annotation.Nullable Map<String, Integer> pageRotations) {
    this.pageRotations = JsonNullable.<Map<String, Integer>>of(pageRotations);
    return this;
  }

  public RotatePdfRequest putPageRotationsItem(String key, Integer pageRotationsItem) {
    if (this.pageRotations == null || !this.pageRotations.isPresent()) {
      this.pageRotations = JsonNullable.<Map<String, Integer>>of(new HashMap<>());
    }
    try {
      this.pageRotations.get().put(key, pageRotationsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get pageRotations
   * @return pageRotations
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Integer> getPageRotations() {
        return pageRotations.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAGE_ROTATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Integer>> getPageRotations_JsonNullable() {
    return pageRotations;
  }
  
  @JsonProperty(JSON_PROPERTY_PAGE_ROTATIONS)
  public void setPageRotations_JsonNullable(JsonNullable<Map<String, Integer>> pageRotations) {
    this.pageRotations = pageRotations;
  }

  public void setPageRotations(@jakarta.annotation.Nullable Map<String, Integer> pageRotations) {
    this.pageRotations = JsonNullable.<Map<String, Integer>>of(pageRotations);
  }


  /**
   * Return true if this RotatePdfRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RotatePdfRequest rotatePdfRequest = (RotatePdfRequest) o;
    return Objects.equals(this.exportType, rotatePdfRequest.exportType) &&
        Objects.equals(this.expiration, rotatePdfRequest.expiration) &&
        equalsNullable(this.filename, rotatePdfRequest.filename) &&
        equalsNullable(this.pdfUrl, rotatePdfRequest.pdfUrl) &&
        equalsNullable(this.pdfBase64, rotatePdfRequest.pdfBase64) &&
        equalsNullable(this.rotation, rotatePdfRequest.rotation) &&
        equalsNullable(this.pageRotations, rotatePdfRequest.pageRotations);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportType, expiration, hashCodeNullable(filename), hashCodeNullable(pdfUrl), hashCodeNullable(pdfBase64), hashCodeNullable(rotation), hashCodeNullable(pageRotations));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RotatePdfRequest {\n");
    sb.append("    exportType: ").append(toIndentedString(exportType)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    pdfUrl: ").append(toIndentedString(pdfUrl)).append("\n");
    sb.append("    pdfBase64: ").append(toIndentedString(pdfBase64)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("    pageRotations: ").append(toIndentedString(pageRotations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `export_type` to the URL query string
    if (getExportType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexport_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExportType()))));
    }

    // add `expiration` to the URL query string
    if (getExpiration() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiration()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `pdf_url` to the URL query string
    if (getPdfUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spdf_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPdfUrl()))));
    }

    // add `pdf_base64` to the URL query string
    if (getPdfBase64() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spdf_base64%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPdfBase64()))));
    }

    // add `rotation` to the URL query string
    if (getRotation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srotation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRotation()))));
    }

    // add `page_rotations` to the URL query string
    if (getPageRotations() != null) {
      for (String _key : getPageRotations().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spage_rotations%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getPageRotations().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getPageRotations().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

