/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Request model for S3 configuration
 */
@JsonPropertyOrder({
  S3ConfigRequest.JSON_PROPERTY_ENDPOINT_URL,
  S3ConfigRequest.JSON_PROPERTY_ACCESS_KEY_ID,
  S3ConfigRequest.JSON_PROPERTY_SECRET_ACCESS_KEY,
  S3ConfigRequest.JSON_PROPERTY_BUCKET_NAME,
  S3ConfigRequest.JSON_PROPERTY_DEFAULT_PREFIX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class S3ConfigRequest {
  public static final String JSON_PROPERTY_ENDPOINT_URL = "endpoint_url";
  @jakarta.annotation.Nonnull
  private String endpointUrl;

  public static final String JSON_PROPERTY_ACCESS_KEY_ID = "access_key_id";
  @jakarta.annotation.Nonnull
  private String accessKeyId;

  public static final String JSON_PROPERTY_SECRET_ACCESS_KEY = "secret_access_key";
  private JsonNullable<String> secretAccessKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BUCKET_NAME = "bucket_name";
  @jakarta.annotation.Nonnull
  private String bucketName;

  public static final String JSON_PROPERTY_DEFAULT_PREFIX = "default_prefix";
  @jakarta.annotation.Nullable
  private String defaultPrefix = "";

  public S3ConfigRequest() { 
  }

  public S3ConfigRequest endpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
    return this;
  }

  /**
   * S3-compatible endpoint URL. Must start with https://
   * @return endpointUrl
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEndpointUrl() {
    return endpointUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }


  public S3ConfigRequest accessKeyId(@jakarta.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

  /**
   * Access key ID for S3 authentication
   * @return accessKeyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCESS_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccessKeyId() {
    return accessKeyId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessKeyId(@jakarta.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }


  public S3ConfigRequest secretAccessKey(@jakarta.annotation.Nullable String secretAccessKey) {
    this.secretAccessKey = JsonNullable.<String>of(secretAccessKey);
    return this;
  }

  /**
   * Get secretAccessKey
   * @return secretAccessKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSecretAccessKey() {
        return secretAccessKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SECRET_ACCESS_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSecretAccessKey_JsonNullable() {
    return secretAccessKey;
  }
  
  @JsonProperty(JSON_PROPERTY_SECRET_ACCESS_KEY)
  public void setSecretAccessKey_JsonNullable(JsonNullable<String> secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
  }

  public void setSecretAccessKey(@jakarta.annotation.Nullable String secretAccessKey) {
    this.secretAccessKey = JsonNullable.<String>of(secretAccessKey);
  }


  public S3ConfigRequest bucketName(@jakarta.annotation.Nonnull String bucketName) {
    this.bucketName = bucketName;
    return this;
  }

  /**
   * S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)
   * @return bucketName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUCKET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBucketName() {
    return bucketName;
  }


  @JsonProperty(value = JSON_PROPERTY_BUCKET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBucketName(@jakarta.annotation.Nonnull String bucketName) {
    this.bucketName = bucketName;
  }


  public S3ConfigRequest defaultPrefix(@jakarta.annotation.Nullable String defaultPrefix) {
    this.defaultPrefix = defaultPrefix;
    return this;
  }

  /**
   * Default path prefix for uploaded files. Can include slashes for folder structure
   * @return defaultPrefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDefaultPrefix() {
    return defaultPrefix;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultPrefix(@jakarta.annotation.Nullable String defaultPrefix) {
    this.defaultPrefix = defaultPrefix;
  }


  /**
   * Return true if this S3ConfigRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3ConfigRequest s3ConfigRequest = (S3ConfigRequest) o;
    return Objects.equals(this.endpointUrl, s3ConfigRequest.endpointUrl) &&
        Objects.equals(this.accessKeyId, s3ConfigRequest.accessKeyId) &&
        equalsNullable(this.secretAccessKey, s3ConfigRequest.secretAccessKey) &&
        Objects.equals(this.bucketName, s3ConfigRequest.bucketName) &&
        Objects.equals(this.defaultPrefix, s3ConfigRequest.defaultPrefix);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointUrl, accessKeyId, hashCodeNullable(secretAccessKey), bucketName, defaultPrefix);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S3ConfigRequest {\n");
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    secretAccessKey: ").append(toIndentedString(secretAccessKey)).append("\n");
    sb.append("    bucketName: ").append(toIndentedString(bucketName)).append("\n");
    sb.append("    defaultPrefix: ").append(toIndentedString(defaultPrefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `endpoint_url` to the URL query string
    if (getEndpointUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointUrl()))));
    }

    // add `access_key_id` to the URL query string
    if (getAccessKeyId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccess_key_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccessKeyId()))));
    }

    // add `secret_access_key` to the URL query string
    if (getSecretAccessKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecret_access_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecretAccessKey()))));
    }

    // add `bucket_name` to the URL query string
    if (getBucketName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbucket_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBucketName()))));
    }

    // add `default_prefix` to the URL query string
    if (getDefaultPrefix() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefault_prefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefaultPrefix()))));
    }

    return joiner.toString();
  }
}

