/*
 * TemplateFox API
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for S3 configuration (with masked secret)
 */
@JsonPropertyOrder({
  S3ConfigResponse.JSON_PROPERTY_CONFIGURED,
  S3ConfigResponse.JSON_PROPERTY_ENDPOINT_URL,
  S3ConfigResponse.JSON_PROPERTY_ACCESS_KEY_ID,
  S3ConfigResponse.JSON_PROPERTY_SECRET_ACCESS_KEY_MASKED,
  S3ConfigResponse.JSON_PROPERTY_BUCKET_NAME,
  S3ConfigResponse.JSON_PROPERTY_DEFAULT_PREFIX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class S3ConfigResponse {
  public static final String JSON_PROPERTY_CONFIGURED = "configured";
  @jakarta.annotation.Nonnull
  private Boolean configured;

  public static final String JSON_PROPERTY_ENDPOINT_URL = "endpoint_url";
  @jakarta.annotation.Nonnull
  private String endpointUrl;

  public static final String JSON_PROPERTY_ACCESS_KEY_ID = "access_key_id";
  @jakarta.annotation.Nonnull
  private String accessKeyId;

  public static final String JSON_PROPERTY_SECRET_ACCESS_KEY_MASKED = "secret_access_key_masked";
  @jakarta.annotation.Nonnull
  private String secretAccessKeyMasked;

  public static final String JSON_PROPERTY_BUCKET_NAME = "bucket_name";
  @jakarta.annotation.Nonnull
  private String bucketName;

  public static final String JSON_PROPERTY_DEFAULT_PREFIX = "default_prefix";
  @jakarta.annotation.Nonnull
  private String defaultPrefix;

  public S3ConfigResponse() { 
  }

  public S3ConfigResponse configured(@jakarta.annotation.Nonnull Boolean configured) {
    this.configured = configured;
    return this;
  }

  /**
   * Whether S3 is configured
   * @return configured
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIGURED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getConfigured() {
    return configured;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIGURED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfigured(@jakarta.annotation.Nonnull Boolean configured) {
    this.configured = configured;
  }


  public S3ConfigResponse endpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
    return this;
  }

  /**
   * S3-compatible endpoint URL
   * @return endpointUrl
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEndpointUrl() {
    return endpointUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }


  public S3ConfigResponse accessKeyId(@jakarta.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

  /**
   * Access key ID
   * @return accessKeyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCESS_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccessKeyId() {
    return accessKeyId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessKeyId(@jakarta.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }


  public S3ConfigResponse secretAccessKeyMasked(@jakarta.annotation.Nonnull String secretAccessKeyMasked) {
    this.secretAccessKeyMasked = secretAccessKeyMasked;
    return this;
  }

  /**
   * Masked secret access key (shows first 4 and last 4 characters)
   * @return secretAccessKeyMasked
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SECRET_ACCESS_KEY_MASKED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSecretAccessKeyMasked() {
    return secretAccessKeyMasked;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET_ACCESS_KEY_MASKED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecretAccessKeyMasked(@jakarta.annotation.Nonnull String secretAccessKeyMasked) {
    this.secretAccessKeyMasked = secretAccessKeyMasked;
  }


  public S3ConfigResponse bucketName(@jakarta.annotation.Nonnull String bucketName) {
    this.bucketName = bucketName;
    return this;
  }

  /**
   * S3 bucket name
   * @return bucketName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUCKET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBucketName() {
    return bucketName;
  }


  @JsonProperty(value = JSON_PROPERTY_BUCKET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBucketName(@jakarta.annotation.Nonnull String bucketName) {
    this.bucketName = bucketName;
  }


  public S3ConfigResponse defaultPrefix(@jakarta.annotation.Nonnull String defaultPrefix) {
    this.defaultPrefix = defaultPrefix;
    return this;
  }

  /**
   * Default path prefix for uploads
   * @return defaultPrefix
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDefaultPrefix() {
    return defaultPrefix;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefaultPrefix(@jakarta.annotation.Nonnull String defaultPrefix) {
    this.defaultPrefix = defaultPrefix;
  }


  /**
   * Return true if this S3ConfigResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3ConfigResponse s3ConfigResponse = (S3ConfigResponse) o;
    return Objects.equals(this.configured, s3ConfigResponse.configured) &&
        Objects.equals(this.endpointUrl, s3ConfigResponse.endpointUrl) &&
        Objects.equals(this.accessKeyId, s3ConfigResponse.accessKeyId) &&
        Objects.equals(this.secretAccessKeyMasked, s3ConfigResponse.secretAccessKeyMasked) &&
        Objects.equals(this.bucketName, s3ConfigResponse.bucketName) &&
        Objects.equals(this.defaultPrefix, s3ConfigResponse.defaultPrefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configured, endpointUrl, accessKeyId, secretAccessKeyMasked, bucketName, defaultPrefix);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S3ConfigResponse {\n");
    sb.append("    configured: ").append(toIndentedString(configured)).append("\n");
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    secretAccessKeyMasked: ").append(toIndentedString(secretAccessKeyMasked)).append("\n");
    sb.append("    bucketName: ").append(toIndentedString(bucketName)).append("\n");
    sb.append("    defaultPrefix: ").append(toIndentedString(defaultPrefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `configured` to the URL query string
    if (getConfigured() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconfigured%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfigured()))));
    }

    // add `endpoint_url` to the URL query string
    if (getEndpointUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointUrl()))));
    }

    // add `access_key_id` to the URL query string
    if (getAccessKeyId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccess_key_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccessKeyId()))));
    }

    // add `secret_access_key_masked` to the URL query string
    if (getSecretAccessKeyMasked() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecret_access_key_masked%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecretAccessKeyMasked()))));
    }

    // add `bucket_name` to the URL query string
    if (getBucketName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbucket_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBucketName()))));
    }

    // add `default_prefix` to the URL query string
    if (getDefaultPrefix() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefault_prefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefaultPrefix()))));
    }

    return joiner.toString();
  }
}

