/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.TemplateFieldSpec;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.templatefox.sdk.ApiClient;
import com.templatefox.sdk.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
@JsonDeserialize(using=Spec.SpecDeserializer.class)
@JsonSerialize(using = Spec.SpecSerializer.class)
public class Spec extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Spec.class.getName());

    public static class SpecSerializer extends StdSerializer<Spec> {
        public SpecSerializer(Class<Spec> t) {
            super(t);
        }

        public SpecSerializer() {
            this(null);
        }

        @Override
        public void serialize(Spec value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SpecDeserializer extends StdDeserializer<Spec> {
        public SpecDeserializer() {
            this(Spec.class);
        }

        public SpecDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public Spec deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize List<TemplateFieldSpec>
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(List<TemplateFieldSpec>.class);
                Spec ret = new Spec();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Spec'", e);
            }

            // deserialize TemplateFieldSpec
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(TemplateFieldSpec.class);
                Spec ret = new Spec();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Spec'", e);
            }

            throw new IOException("Failed deserialization for Spec: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public Spec getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            return null;
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public Spec() {
        super("anyOf", Boolean.TRUE);
    }

    public Spec(List<TemplateFieldSpec> o) {
        super("anyOf", Boolean.TRUE);
        setActualInstance(o);
    }

    public Spec(TemplateFieldSpec o) {
        super("anyOf", Boolean.TRUE);
        setActualInstance(o);
    }

    static {
        schemas.put("List<TemplateFieldSpec>", List<TemplateFieldSpec>.class);
        schemas.put("TemplateFieldSpec", TemplateFieldSpec.class);
        JSON.registerDescendants(Spec.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return Spec.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * List<TemplateFieldSpec>, TemplateFieldSpec
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance == null) {
           super.setActualInstance(instance);
           return;
        }

        if (JSON.isInstanceOf(List<TemplateFieldSpec>.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TemplateFieldSpec.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be List<TemplateFieldSpec>, TemplateFieldSpec");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<TemplateFieldSpec>, TemplateFieldSpec
     *
     * @return The actual instance (List<TemplateFieldSpec>, TemplateFieldSpec)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<TemplateFieldSpec>`. If the actual instance is not `List<TemplateFieldSpec>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<TemplateFieldSpec>`
     * @throws ClassCastException if the instance is not `List<TemplateFieldSpec>`
     */
    public List<TemplateFieldSpec> getList<TemplateFieldSpec>() throws ClassCastException {
        return (List<TemplateFieldSpec>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TemplateFieldSpec`. If the actual instance is not `TemplateFieldSpec`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TemplateFieldSpec`
     * @throws ClassCastException if the instance is not `TemplateFieldSpec`
     */
    public TemplateFieldSpec getTemplateFieldSpec() throws ClassCastException {
        return (TemplateFieldSpec)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

