/*
 * TemplateFox API
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Zapier InputFieldsSchema compatible field
 */
@JsonPropertyOrder({
  TemplateField.JSON_PROPERTY_KEY,
  TemplateField.JSON_PROPERTY_LABEL,
  TemplateField.JSON_PROPERTY_TYPE,
  TemplateField.JSON_PROPERTY_REQUIRED,
  TemplateField.JSON_PROPERTY_HELP_TEXT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class TemplateField {
  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nonnull
  private String label;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type = "string";

  public static final String JSON_PROPERTY_REQUIRED = "required";
  @jakarta.annotation.Nullable
  private Boolean required = false;

  public static final String JSON_PROPERTY_HELP_TEXT = "helpText";
  private JsonNullable<String> helpText = JsonNullable.<String>undefined();

  public TemplateField() { 
  }

  public TemplateField key(@jakarta.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Field key/identifier
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }


  public TemplateField label(@jakarta.annotation.Nonnull String label) {
    this.label = label;
    return this;
  }

  /**
   * Human-readable label
   * @return label
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabel() {
    return label;
  }


  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@jakarta.annotation.Nonnull String label) {
    this.label = label;
  }


  public TemplateField type(@jakarta.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Field type: string, integer, number, boolean
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }


  public TemplateField required(@jakarta.annotation.Nullable Boolean required) {
    this.required = required;
    return this;
  }

  /**
   * Whether the field is required
   * @return required
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequired(@jakarta.annotation.Nullable Boolean required) {
    this.required = required;
  }


  public TemplateField helpText(@jakarta.annotation.Nullable String helpText) {
    this.helpText = JsonNullable.<String>of(helpText);
    return this;
  }

  /**
   * Get helpText
   * @return helpText
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getHelpText() {
        return helpText.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HELP_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getHelpText_JsonNullable() {
    return helpText;
  }
  
  @JsonProperty(JSON_PROPERTY_HELP_TEXT)
  public void setHelpText_JsonNullable(JsonNullable<String> helpText) {
    this.helpText = helpText;
  }

  public void setHelpText(@jakarta.annotation.Nullable String helpText) {
    this.helpText = JsonNullable.<String>of(helpText);
  }


  /**
   * Return true if this TemplateField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateField templateField = (TemplateField) o;
    return Objects.equals(this.key, templateField.key) &&
        Objects.equals(this.label, templateField.label) &&
        Objects.equals(this.type, templateField.type) &&
        Objects.equals(this.required, templateField.required) &&
        equalsNullable(this.helpText, templateField.helpText);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, label, type, required, hashCodeNullable(helpText));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateField {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `label` to the URL query string
    if (getLabel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slabel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabel()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `required` to the URL query string
    if (getRequired() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequired()))));
    }

    // add `helpText` to the URL query string
    if (getHelpText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shelpText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHelpText()))));
    }

    return joiner.toString();
  }
}

