/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.Transaction;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Response for transactions list endpoint
 */
@JsonPropertyOrder({
  TransactionsResponse.JSON_PROPERTY_TRANSACTIONS,
  TransactionsResponse.JSON_PROPERTY_TOTAL,
  TransactionsResponse.JSON_PROPERTY_LIMIT,
  TransactionsResponse.JSON_PROPERTY_OFFSET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class TransactionsResponse {
  public static final String JSON_PROPERTY_TRANSACTIONS = "transactions";
  @jakarta.annotation.Nonnull
  private List<Transaction> transactions = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL = "total";
  @jakarta.annotation.Nonnull
  private Integer total;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  @jakarta.annotation.Nonnull
  private Integer offset;

  public TransactionsResponse() { 
  }

  public TransactionsResponse transactions(@jakarta.annotation.Nonnull List<Transaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TransactionsResponse addTransactionsItem(Transaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

  /**
   * Get transactions
   * @return transactions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Transaction> getTransactions() {
    return transactions;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactions(@jakarta.annotation.Nonnull List<Transaction> transactions) {
    this.transactions = transactions;
  }


  public TransactionsResponse total(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Total number of transactions
   * @return total
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
  }


  public TransactionsResponse limit(@jakarta.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Number of records returned
   * @return limit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@jakarta.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public TransactionsResponse offset(@jakarta.annotation.Nonnull Integer offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Number of records skipped
   * @return offset
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getOffset() {
    return offset;
  }


  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOffset(@jakarta.annotation.Nonnull Integer offset) {
    this.offset = offset;
  }


  /**
   * Return true if this TransactionsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionsResponse transactionsResponse = (TransactionsResponse) o;
    return Objects.equals(this.transactions, transactionsResponse.transactions) &&
        Objects.equals(this.total, transactionsResponse.total) &&
        Objects.equals(this.limit, transactionsResponse.limit) &&
        Objects.equals(this.offset, transactionsResponse.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions, total, limit, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionsResponse {\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactions` to the URL query string
    if (getTransactions() != null) {
      for (int i = 0; i < getTransactions().size(); i++) {
        if (getTransactions().get(i) != null) {
          joiner.add(getTransactions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stransactions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `offset` to the URL query string
    if (getOffset() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soffset%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOffset()))));
    }

    return joiner.toString();
  }
}

