/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.templatefox.sdk.ApiClient;
/**
 * Transaction record
 */
@JsonPropertyOrder({
  Transaction.JSON_PROPERTY_TRANSACTION_REF,
  Transaction.JSON_PROPERTY_TRANSACTION_TYPE,
  Transaction.JSON_PROPERTY_TEMPLATE_ID,
  Transaction.JSON_PROPERTY_EXEC_TM,
  Transaction.JSON_PROPERTY_CREDITS,
  Transaction.JSON_PROPERTY_CREATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class Transaction {
  public static final String JSON_PROPERTY_TRANSACTION_REF = "transaction_ref";
  @jakarta.annotation.Nonnull
  private String transactionRef;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transaction_type";
  @jakarta.annotation.Nonnull
  private String transactionType;

  public static final String JSON_PROPERTY_TEMPLATE_ID = "template_id";
  private JsonNullable<String> templateId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXEC_TM = "exec_tm";
  private JsonNullable<Integer> execTm = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CREDITS = "credits";
  @jakarta.annotation.Nonnull
  private Integer credits;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private String createdAt;

  public Transaction() { 
  }

  public Transaction transactionRef(@jakarta.annotation.Nonnull String transactionRef) {
    this.transactionRef = transactionRef;
    return this;
  }

  /**
   * Unique transaction reference (UUID)
   * @return transactionRef
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionRef() {
    return transactionRef;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionRef(@jakarta.annotation.Nonnull String transactionRef) {
    this.transactionRef = transactionRef;
  }


  public Transaction transactionType(@jakarta.annotation.Nonnull String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Transaction type: PDFGEN, PURCHASE, REFUND, BONUS
   * @return transactionType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionType(@jakarta.annotation.Nonnull String transactionType) {
    this.transactionType = transactionType;
  }


  public Transaction templateId(@jakarta.annotation.Nullable String templateId) {
    this.templateId = JsonNullable.<String>of(templateId);
    return this;
  }

  /**
   * Get templateId
   * @return templateId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getTemplateId() {
        return templateId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTemplateId_JsonNullable() {
    return templateId;
  }
  
  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  public void setTemplateId_JsonNullable(JsonNullable<String> templateId) {
    this.templateId = templateId;
  }

  public void setTemplateId(@jakarta.annotation.Nullable String templateId) {
    this.templateId = JsonNullable.<String>of(templateId);
  }


  public Transaction execTm(@jakarta.annotation.Nullable Integer execTm) {
    this.execTm = JsonNullable.<Integer>of(execTm);
    return this;
  }

  /**
   * Get execTm
   * @return execTm
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getExecTm() {
        return execTm.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXEC_TM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExecTm_JsonNullable() {
    return execTm;
  }
  
  @JsonProperty(JSON_PROPERTY_EXEC_TM)
  public void setExecTm_JsonNullable(JsonNullable<Integer> execTm) {
    this.execTm = execTm;
  }

  public void setExecTm(@jakarta.annotation.Nullable Integer execTm) {
    this.execTm = JsonNullable.<Integer>of(execTm);
  }


  public Transaction credits(@jakarta.annotation.Nonnull Integer credits) {
    this.credits = credits;
    return this;
  }

  /**
   * Credits consumed (positive) or added (negative)
   * @return credits
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCredits() {
    return credits;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDITS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredits(@jakarta.annotation.Nonnull Integer credits) {
    this.credits = credits;
  }


  public Transaction createdAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * ISO 8601 timestamp
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this Transaction object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.transactionRef, transaction.transactionRef) &&
        Objects.equals(this.transactionType, transaction.transactionType) &&
        equalsNullable(this.templateId, transaction.templateId) &&
        equalsNullable(this.execTm, transaction.execTm) &&
        Objects.equals(this.credits, transaction.credits) &&
        Objects.equals(this.createdAt, transaction.createdAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionRef, transactionType, hashCodeNullable(templateId), hashCodeNullable(execTm), credits, createdAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    transactionRef: ").append(toIndentedString(transactionRef)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    execTm: ").append(toIndentedString(execTm)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transaction_ref` to the URL query string
    if (getTransactionRef() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransaction_ref%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionRef()))));
    }

    // add `transaction_type` to the URL query string
    if (getTransactionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransaction_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionType()))));
    }

    // add `template_id` to the URL query string
    if (getTemplateId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateId()))));
    }

    // add `exec_tm` to the URL query string
    if (getExecTm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexec_tm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExecTm()))));
    }

    // add `credits` to the URL query string
    if (getCredits() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scredits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCredits()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

