/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppRoutersV1PdfExportType
 */
class AppRoutersV1PdfExportTypeTest {
    /**
     * Model tests for AppRoutersV1PdfExportType
     */
    @Test
    void testAppRoutersV1PdfExportType() {
        // TODO: test AppRoutersV1PdfExportType
    }

}
