/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.ExportType;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePdfRequest
 */
class CreatePdfRequestTest {
    private final CreatePdfRequest model = new CreatePdfRequest();

    /**
     * Model tests for CreatePdfRequest
     */
    @Test
    void testCreatePdfRequest() {
        // TODO: test CreatePdfRequest
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'exportType'
     */
    @Test
    void exportTypeTest() {
        // TODO: test exportType
    }

    /**
     * Test the property 'expiration'
     */
    @Test
    void expirationTest() {
        // TODO: test expiration
    }

    /**
     * Test the property 'filename'
     */
    @Test
    void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'storeS3'
     */
    @Test
    void storeS3Test() {
        // TODO: test storeS3
    }

    /**
     * Test the property 's3Filepath'
     */
    @Test
    void s3FilepathTest() {
        // TODO: test s3Filepath
    }

    /**
     * Test the property 's3Bucket'
     */
    @Test
    void s3BucketTest() {
        // TODO: test s3Bucket
    }

}
