/*
 * TemplateFox API
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePdfResponse
 */
class CreatePdfResponseTest {
    private final CreatePdfResponse model = new CreatePdfResponse();

    /**
     * Model tests for CreatePdfResponse
     */
    @Test
    void testCreatePdfResponse() {
        // TODO: test CreatePdfResponse
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'filename'
     */
    @Test
    void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'creditsRemaining'
     */
    @Test
    void creditsRemainingTest() {
        // TODO: test creditsRemaining
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    void expiresInTest() {
        // TODO: test expiresIn
    }

}
