/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.JobStatus;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateAsyncPdfResponse
 */
class CreateAsyncPdfResponseTest {
    private final CreateAsyncPdfResponse model = new CreateAsyncPdfResponse();

    /**
     * Model tests for CreateAsyncPdfResponse
     */
    @Test
    void testCreateAsyncPdfResponse() {
        // TODO: test CreateAsyncPdfResponse
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'creditsRemaining'
     */
    @Test
    void creditsRemainingTest() {
        // TODO: test creditsRemaining
    }

}
