/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.1.dev2+gfe6303fdd.d20260209
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExportType
 */
class ExportTypeTest {
    /**
     * Model tests for ExportType
     */
    @Test
    void testExportType() {
        // TODO: test ExportType
    }

}
