/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.JobStatus;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobStatusResponse
 */
class JobStatusResponseTest {
    private final JobStatusResponse model = new JobStatusResponse();

    /**
     * Model tests for JobStatusResponse
     */
    @Test
    void testJobStatusResponse() {
        // TODO: test JobStatusResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'exportType'
     */
    @Test
    void exportTypeTest() {
        // TODO: test exportType
    }

    /**
     * Test the property 'filename'
     */
    @Test
    void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'storeS3'
     */
    @Test
    void storeS3Test() {
        // TODO: test storeS3
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'resultUrl'
     */
    @Test
    void resultUrlTest() {
        // TODO: test resultUrl
    }

    /**
     * Test the property 'resultFilename'
     */
    @Test
    void resultFilenameTest() {
        // TODO: test resultFilename
    }

    /**
     * Test the property 'resultExpiresAt'
     */
    @Test
    void resultExpiresAtTest() {
        // TODO: test resultExpiresAt
    }

    /**
     * Test the property 'resultS3Bucket'
     */
    @Test
    void resultS3BucketTest() {
        // TODO: test resultS3Bucket
    }

    /**
     * Test the property 'resultS3Key'
     */
    @Test
    void resultS3KeyTest() {
        // TODO: test resultS3Key
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    void errorCodeTest() {
        // TODO: test errorCode
    }

}
