/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.AppRoutersV1PdfToolsExportType;
import com.templatefox.sdk.model.PdfInput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MergePdfRequest
 */
class MergePdfRequestTest {
    private final MergePdfRequest model = new MergePdfRequest();

    /**
     * Model tests for MergePdfRequest
     */
    @Test
    void testMergePdfRequest() {
        // TODO: test MergePdfRequest
    }

    /**
     * Test the property 'exportType'
     */
    @Test
    void exportTypeTest() {
        // TODO: test exportType
    }

    /**
     * Test the property 'expiration'
     */
    @Test
    void expirationTest() {
        // TODO: test expiration
    }

    /**
     * Test the property 'filename'
     */
    @Test
    void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'pdfs'
     */
    @Test
    void pdfsTest() {
        // TODO: test pdfs
    }

}
