/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for S3ConfigRequest
 */
class S3ConfigRequestTest {
    private final S3ConfigRequest model = new S3ConfigRequest();

    /**
     * Model tests for S3ConfigRequest
     */
    @Test
    void testS3ConfigRequest() {
        // TODO: test S3ConfigRequest
    }

    /**
     * Test the property 'endpointUrl'
     */
    @Test
    void endpointUrlTest() {
        // TODO: test endpointUrl
    }

    /**
     * Test the property 'accessKeyId'
     */
    @Test
    void accessKeyIdTest() {
        // TODO: test accessKeyId
    }

    /**
     * Test the property 'secretAccessKey'
     */
    @Test
    void secretAccessKeyTest() {
        // TODO: test secretAccessKey
    }

    /**
     * Test the property 'bucketName'
     */
    @Test
    void bucketNameTest() {
        // TODO: test bucketName
    }

    /**
     * Test the property 'defaultPrefix'
     */
    @Test
    void defaultPrefixTest() {
        // TODO: test defaultPrefix
    }

}
