/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.templatefox.sdk.model.TemplateFieldSpec;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplateField
 */
class TemplateFieldTest {
    private final TemplateField model = new TemplateField();

    /**
     * Model tests for TemplateField
     */
    @Test
    void testTemplateField() {
        // TODO: test TemplateField
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'label'
     */
    @Test
    void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'required'
     */
    @Test
    void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'helpText'
     */
    @Test
    void helpTextTest() {
        // TODO: test helpText
    }

    /**
     * Test the property 'spec'
     */
    @Test
    void specTest() {
        // TODO: test spec
    }

}
