/*
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.templatefox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Transaction
 */
class TransactionTest {
    private final Transaction model = new Transaction();

    /**
     * Model tests for Transaction
     */
    @Test
    void testTransaction() {
        // TODO: test Transaction
    }

    /**
     * Test the property 'transactionRef'
     */
    @Test
    void transactionRefTest() {
        // TODO: test transactionRef
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    void transactionTypeTest() {
        // TODO: test transactionType
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'execTm'
     */
    @Test
    void execTmTest() {
        // TODO: test execTm
    }

    /**
     * Test the property 'credits'
     */
    @Test
    void creditsTest() {
        // TODO: test credits
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
